---
global:
  scrape_interval: '5s'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
        - 'localhost:9090'

  - job_name: 'ui'
    static_configs:
      - targets:
        - 'ui:9292'

  - job_name: 'comment'
    static_configs:
      - targets:
        - 'comment:9292'

  - job_name: 'node'
    static_configs:
      - targets:
        -  'node-exporter:9100'

  - job_name: 'mongodb'
    scrape_interval: 300s
    scrape_timeout: 300s
    static_configs:
      - targets:
        -  'mongodb-exporter:9001'

  - job_name: 'cloudprober'
    static_configs:
      - targets:
        - 'cloudprober-exporter:9313' 

  - job_name: 'cadvisor'
    static_configs:
      - targets:
        - 'cadvisor:8080'

  - job_name: 'post'
    static_configs:
      - targets:
        - 'post:5000'

  - job_name: 'docker'
    static_configs:
    - targets:
      - '10.0.1.1:9393'

  - job_name: 'telegraf'
    static_configs:
    - targets:
      - 'telegraf:9273'

rule_files:
  - "alerts.yml"

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

